# coding: utf-8

"""
    Dkube api server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FeatureServiceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'features': 'list[str]',
        'project': 'str',
        'userid': 'str'
    }

    attribute_map = {
        'name': 'name',
        'features': 'features',
        'project': 'project',
        'userid': 'userid'
    }

    def __init__(self, name=None, features=None, project=None, userid=None):  # noqa: E501
        """FeatureServiceResponse - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._features = None
        self._project = None
        self._userid = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if features is not None:
            self.features = features
        if project is not None:
            self.project = project
        if userid is not None:
            self.userid = userid

    @property
    def name(self):
        """Gets the name of this FeatureServiceResponse.  # noqa: E501


        :return: The name of this FeatureServiceResponse.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FeatureServiceResponse.


        :param name: The name of this FeatureServiceResponse.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def features(self):
        """Gets the features of this FeatureServiceResponse.  # noqa: E501


        :return: The features of this FeatureServiceResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this FeatureServiceResponse.


        :param features: The features of this FeatureServiceResponse.  # noqa: E501
        :type: list[str]
        """

        self._features = features

    @property
    def project(self):
        """Gets the project of this FeatureServiceResponse.  # noqa: E501


        :return: The project of this FeatureServiceResponse.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this FeatureServiceResponse.


        :param project: The project of this FeatureServiceResponse.  # noqa: E501
        :type: str
        """

        self._project = project

    @property
    def userid(self):
        """Gets the userid of this FeatureServiceResponse.  # noqa: E501


        :return: The userid of this FeatureServiceResponse.  # noqa: E501
        :rtype: str
        """
        return self._userid

    @userid.setter
    def userid(self, userid):
        """Sets the userid of this FeatureServiceResponse.


        :param userid: The userid of this FeatureServiceResponse.  # noqa: E501
        :type: str
        """

        self._userid = userid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FeatureServiceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FeatureServiceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
