# coding: utf-8

"""
    Dkube api server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ModelCatalogItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'owner': 'str',
        'uuid': 'str',
        'update_timestamp': 'TimeStamps'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'owner': 'owner',
        'uuid': 'UUID',
        'update_timestamp': 'updateTimestamp'
    }

    def __init__(self, name=None, description=None, owner=None, uuid=None, update_timestamp=None):  # noqa: E501
        """ModelCatalogItem - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._description = None
        self._owner = None
        self._uuid = None
        self._update_timestamp = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if owner is not None:
            self.owner = owner
        if uuid is not None:
            self.uuid = uuid
        if update_timestamp is not None:
            self.update_timestamp = update_timestamp

    @property
    def name(self):
        """Gets the name of this ModelCatalogItem.  # noqa: E501


        :return: The name of this ModelCatalogItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ModelCatalogItem.


        :param name: The name of this ModelCatalogItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this ModelCatalogItem.  # noqa: E501


        :return: The description of this ModelCatalogItem.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ModelCatalogItem.


        :param description: The description of this ModelCatalogItem.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def owner(self):
        """Gets the owner of this ModelCatalogItem.  # noqa: E501


        :return: The owner of this ModelCatalogItem.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this ModelCatalogItem.


        :param owner: The owner of this ModelCatalogItem.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def uuid(self):
        """Gets the uuid of this ModelCatalogItem.  # noqa: E501


        :return: The uuid of this ModelCatalogItem.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this ModelCatalogItem.


        :param uuid: The uuid of this ModelCatalogItem.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def update_timestamp(self):
        """Gets the update_timestamp of this ModelCatalogItem.  # noqa: E501


        :return: The update_timestamp of this ModelCatalogItem.  # noqa: E501
        :rtype: TimeStamps
        """
        return self._update_timestamp

    @update_timestamp.setter
    def update_timestamp(self, update_timestamp):
        """Sets the update_timestamp of this ModelCatalogItem.


        :param update_timestamp: The update_timestamp of this ModelCatalogItem.  # noqa: E501
        :type: TimeStamps
        """

        self._update_timestamp = update_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelCatalogItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelCatalogItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
