# coding: utf-8

"""
    Dkube api server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.3.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PerformanceMonitoringSoftThresholdDef(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'baseline': 'float',
        'soft': 'float'
    }

    attribute_map = {
        'baseline': 'baseline',
        'soft': 'soft'
    }

    def __init__(self, baseline=None, soft=None):  # noqa: E501
        """PerformanceMonitoringSoftThresholdDef - a model defined in Swagger"""  # noqa: E501

        self._baseline = None
        self._soft = None
        self.discriminator = None

        if baseline is not None:
            self.baseline = baseline
        if soft is not None:
            self.soft = soft

    @property
    def baseline(self):
        """Gets the baseline of this PerformanceMonitoringSoftThresholdDef.  # noqa: E501


        :return: The baseline of this PerformanceMonitoringSoftThresholdDef.  # noqa: E501
        :rtype: float
        """
        return self._baseline

    @baseline.setter
    def baseline(self, baseline):
        """Sets the baseline of this PerformanceMonitoringSoftThresholdDef.


        :param baseline: The baseline of this PerformanceMonitoringSoftThresholdDef.  # noqa: E501
        :type: float
        """

        self._baseline = baseline

    @property
    def soft(self):
        """Gets the soft of this PerformanceMonitoringSoftThresholdDef.  # noqa: E501


        :return: The soft of this PerformanceMonitoringSoftThresholdDef.  # noqa: E501
        :rtype: float
        """
        return self._soft

    @soft.setter
    def soft(self, soft):
        """Sets the soft of this PerformanceMonitoringSoftThresholdDef.


        :param soft: The soft of this PerformanceMonitoringSoftThresholdDef.  # noqa: E501
        :type: float
        """

        self._soft = soft

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PerformanceMonitoringSoftThresholdDef, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PerformanceMonitoringSoftThresholdDef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
